name:
  asd: sd
  sdf: sdf

port: COM4

devices:
  - id: ebefef21
    eep: fasdf13
  - id: abebebas
    eep: 4gf23f32

database:
  url: https://influxdb.com
  org: organization
  token: influxdb-token
  bucket: bucket
