FROM alpine:latest AS openssl-stage

RUN apk add --no-cache openssl

WORKDIR /certs
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout key.pem -out cert.pem -subj "/CN=localhost"

FROM nginx:latest

COPY --from=openssl-stage /certs /etc/nginx/certs
COPY ./compose/nginx/nginx.conf /etc/nginx/nginx.conf

# Expose ports
EXPOSE 80
EXPOSE 443

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]