services:
  timescaledb:
    image: timescale/timescaledb-ha:pg17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=enohub
      - POSTGRES_USER=enohub
      - POSTGRES_PASSWORD=enohub
    volumes:
      - timescaledb_data:/home/postgres/pgdata/data
      - ./compose/timescaledb/init.sql:/docker-entrypoint-initdb.d/init.sql
  grafana:
    image: grafana/grafana:11.5.2
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./compose/grafana/dashboards:/var/lib/grafana/dashboards
      - ./compose/grafana/provisioning:/etc/grafana/provisioning
      # - ./compose/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
    environment:
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
    restart: on-failure

  enohub:
    image: ghcr.io/yusufcanb/enohub:0.3.1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config.yml:/opt/enocean/enohub/config.yml
    devices:
      - /dev/ttyUSB0
    restart: on-failure
    depends_on:
      - timescaledb

  nginx:
    image: ghcr.io/yusufcanb/enohub-proxy:0.3.1
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure
    depends_on:
      - grafana
      - timescaledb

volumes:
  timescaledb_data:
  grafana-storage:
