version: '3'

services:
    influxdb:
      image: influxdb:2.6-alpine
      environment:
        - DOCKER_INFLUXDB_INIT_MODE=setup
        - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
        - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
        - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
        - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
        - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
      volumes:
        - /var/lib/influxdb2:/var/lib/influxdb2
      ports:
        - 8086:8086

    grafana:
      image: grafana/grafana:10.0.10-ubuntu
      ports:
        - '3000:3000'
      volumes:
        - grafana-storage:/var/lib/grafana
        - ./compose/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
        - ./compose/grafana/dashboards:/var/lib/grafana/dashboards
      environment:
        - GF_PANELS_DISABLE_SANITIZE_HTML=true
      restart: on-failure

    enohub:
      image: ghcr.io/yusufcanb/enohub:0.3.0
      ports:
        - '80:80'
        - '443:443'
      restart: on-failure
      depends_on:
        - influxdb   

    nginx:
      image: ghcr.io/yusufcanb/enohub-proxy:0.3.0
      ports:
        - '80:80'
        - '443:443'
      restart: on-failure
      depends_on:
        - grafana
        - influxdb

volumes:
  grafana-storage:
