port: /dev/ttyUSB0 # Serial port which EnOcean USB 3000 connected.

devices: # Array of registered devices map. IDs can be found on the backside of every device.
  - id: 04211ABE
    name: sensor-1
    eep: d2-14-41
    group: office
  - id: 04211945
    name: sensor-2
    eep: d2-14-41
    group: office
  - id: 04211AA6
    name: sensor-3
    eep: d2-14-41
    group: kitchen
  - id: 0420FCCD
    name: co2
    eep: a5-09-09
    group: living-room

database:
  host: "localhost"
  port: 5432
  user: "enohub"
  password: "enohub"
  dbname: "enohub"
  schema: "public"
