name: kitchen # Display name of the sensor group. E.g living-room, kitchen, keller.
port: /dev/ttyUSB0 # Serial port which EnOcean USB 3000 connected.

devices: # Array of registered devices map. IDs can be found on the backside of every device.
  - id: 04211ABE
    name: sensor-1
    eep:	d2-14-41
  - id: 04211945
    name: sensor-2
    eep:	d2-14-41
  - id: 04211AA6
    name: sensor-3
    eep:	d2-14-41
  - id: 0420FCCD
    name: co2
    eep:	a5-09-09

database:  # Influx Time-Series database configuration
  url: https://my-influxdb-instance.com  # URL of the influxdb instance
  org: INFLUXDB_ORGANIZATION # Organization name of the account
  token: READ_WRITE_TOKEN # Access Token for the client
  bucket: BUCKET_NAME # Bucket name for the data records
  