site_name: EnOcean Hub

docs_dir: markdown/
base_dir: docs/
site_dir: docs/

repo_url: https://github.com/yusufcanb/enohub.git
repo_name: Enohub

nav:
  - Overview: index.md
  - Configuration: configuration.md
  - Installation: installation.md
  - Grafana: dashboard.md

theme:
  name: yeti
  nav_style: dark
