version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        command: tail -f /dev/null
    influxdb:
      image: influxdb:2.6-alpine
      environment:
        - DOCKER_INFLUXDB_INIT_MODE=setup
        - DOCKER_INFLUXDB_INIT_USERNAME=devcontainer
        - DOCKER_INFLUXDB_INIT_PASSWORD=devcontainer
        - DOCKER_INFLUXDB_INIT_ORG=default
        - DOCKER_INFLUXDB_INIT_BUCKET=default
        - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=devcontainer-token
      volumes:
        - influxdbv2:/var/lib/influxdb2
      ports:
        - 8086:8086

volumes:
  influxdbv2:
