{
 "title": "Enohub Default Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "device_group",
    "label": "Device Group",
    "query": "SELECT DISTINCT(device_group) FROM ts_kv_latest;"
   },
   {
    "name": "device_name",
    "query": "SELECT DISTINCT(device_name) FROM ts_kv_latest WHERE device_group = ANY(ARRAY[${device_group}]);"
   }
  ]
 },
 "panels": [
  { "title": "${device_group}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "device_group" },
  {
   "title": "TMP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TMP\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"sensor_group\"] == \"${sensor_group}\")\r\n  |> drop(columns: [\"sensor_id\", \"sensor_name\"])\r\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "rawSql": "SELECT\r\n  time_bucket('${__interval}', to_timestamp(ts::bigint / 1000)) AS time,\r\n  avg(COALESCE(long_v, dbl_v)) AS value\r\nFROM ts_kv\r\nWHERE\r\n  key = 'tmp'\r\n  AND ts >= EXTRACT(EPOCH FROM NOW() - INTERVAL '1 hour') * 1000\r\n  AND ts < EXTRACT(EPOCH FROM NOW()) * 1000\r\n  AND device_group = '${device_group}'\r\nGROUP BY time\r\nORDER BY time\r\nLIMIT 25;"
    }
   ]
  },
  {
   "title": "HUM",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HUM\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"sensor_group\"] == \"${sensor_group}\")\r\n  |> drop(columns: [\"sensor_id\", \"sensor_name\", \"_field\"])\r\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n  ",
     "rawSql": "SELECT\r\n  time_bucket('${__interval}', to_timestamp(ts::bigint / 1000)) AS time,\r\n  avg(COALESCE(long_v, dbl_v)) AS value\r\nFROM ts_kv\r\nWHERE\r\n  key = 'hum'\r\n  AND ts >= EXTRACT(EPOCH FROM NOW() - INTERVAL '1 hour') * 1000\r\n  AND ts < EXTRACT(EPOCH FROM NOW()) * 1000\r\n  AND device_group = '${device_group}'\r\nGROUP BY time\r\nORDER BY time\r\nLIMIT 25;"
    }
   ]
  },
  {
   "title": "ILL",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ILL\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"sensor_group\"] == \"${sensor_group}\")\r\n  |> drop(columns: [\"sensor_id\", \"sensor_name\"])\r\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "rawSql": "SELECT\r\n  time_bucket('${__interval}', to_timestamp(ts::bigint / 1000)) AS time,\r\n  avg(COALESCE(long_v, dbl_v)) AS value\r\nFROM ts_kv\r\nWHERE\r\n  key = 'ill'\r\n  AND ts >= EXTRACT(EPOCH FROM NOW() - INTERVAL '1 hour') * 1000\r\n  AND ts < EXTRACT(EPOCH FROM NOW()) * 1000\r\n  AND device_group = '${device_group}'\r\nGROUP BY time\r\nORDER BY time\r\nLIMIT 25;"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"CO2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"sensor_group\"] == \"${sensor_group}\")\r\n  |> drop(columns: [\"sensor_id\", \"sensor_name\"])\r\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "rawSql": "SELECT\r\n  time_bucket('${__interval}', to_timestamp(ts :: bigint / 1000)) AS time,\r\n  avg(COALESCE(long_v, dbl_v)) as value\r\nFROM\r\n  ts_kv\r\nWHERE\r\n  key = 'co2'\r\n  AND ts >= ${__from}\r\n  AND ts < ${__to}\r\n  AND device_group = '${device_group}'\r\nGROUP BY\r\n  time\r\nORDER BY\r\n  time;"
    }
   ]
  },
  {
   "title": "TMP (Timeline)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TMP\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"sensor_group\"] == \"${sensor_group}\")\r\n  |> drop(columns: [\"sensor_id\", \"sensor_name\", \"_field\"])\r\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "rawSql": "SELECT\r\n  time_bucket('${__interval}', to_timestamp(ts :: bigint / 1000)) AS time,\r\n  avg(COALESCE(long_v, dbl_v)) as value\r\nFROM\r\n  ts_kv\r\nWHERE\r\n  key = 'tmp'\r\n  AND ts >= ${__from}\r\n  AND ts < ${__to}\r\n  AND device_group = '${device_group}'\r\nGROUP BY\r\n  time\r\nORDER BY\r\n  time;"
    }
   ]
  },
  {
   "title": "Humidity (Timeline)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HUM\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"sensor_group\"] == \"${sensor_group}\")\r\n  |> drop(columns: [\"sensor_id\", \"sensor_name\", \"_field\"])\r\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "rawSql": "SELECT\r\n  time_bucket('${__interval}', to_timestamp(ts :: bigint / 1000)) AS time,\r\n  avg(COALESCE(long_v, dbl_v)) as value\r\nFROM\r\n  ts_kv\r\nWHERE\r\n  key = 'hum'\r\n  AND ts >= ${__from}\r\n  AND ts < ${__to}\r\n  AND device_group = '${device_group}'\r\nGROUP BY\r\n  time\r\nORDER BY\r\n  time;"
    }
   ]
  },
  {
   "title": "Illumination (Timeline)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ILL\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"sensor_group\"] == \"${sensor_group}\")\r\n  |> drop(columns: [\"sensor_id\", \"sensor_name\", \"_field\"])\r\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "rawSql": "SELECT\r\n  time_bucket(\r\n    '${__interval}',\r\n    to_timestamp(ts :: bigint / 1000)\r\n  ) AS time,\r\n  avg(COALESCE(long_v, dbl_v)) as value\r\nFROM\r\n  ts_kv\r\nWHERE\r\n  key = 'ill'\r\n  AND ts >= ${__from}\r\n  AND ts < ${__to}\r\n  AND device_group = '${device_group}'\r\nGROUP BY\r\n  time\r\nORDER BY\r\n  time;"
    }
   ]
  },
  {
   "title": "CO2 (Timeline)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"CO2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"sensor_group\"] == \"${sensor_group}\")\r\n  |> drop(columns: [\"sensor_id\", \"sensor_name\", \"_field\"])\r\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "rawSql": "SELECT\r\n  time_bucket('${__interval}', to_timestamp(ts :: bigint / 1000)) AS time,\r\n  avg(COALESCE(long_v, dbl_v)) as value\r\nFROM\r\n  ts_kv\r\nWHERE\r\n  key = 'co2'\r\n  AND ts >= ${__from}\r\n  AND ts < ${__to}\r\n  AND device_group = '${device_group}'\r\nGROUP BY\r\n  time\r\nORDER BY\r\n  time;"
    }
   ]
  }
 ]
}