name: Push Image to GHCR
on:
  push:
    branches:
      - 'main'
      - 'release/**'
  create:
    tags:
      - v*
jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Init submodules
        run: git submodule update --init --recursive
      - name: Set Environment
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/yusufcanb/enohub:${{ env.RELEASE_VERSION }}
      - name: Login to Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u USERNAME --password-stdin
      - name: Push Image to Github Container Registry
        run: docker push ghcr.io/yusufcanb/enohub:${{ env.RELEASE_VERSION }}
