name: Push Image to GHCR
on:
  push:
    branches:
      - 'main'
      - 'release/**'
  create:
    tags:
      - v*
jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Init submodules
        run: git submodule update --init --recursive
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/yusufcanb/enohub:${{ env.RELEASE_VERSION }}
      - name: Build the Docker image
        run: docker push ghcr.io/yusufcanb/enohub:${{ env.RELEASE_VERSION }}
